final x13125320/AppNameTestify/AppNameTestify/Controllers/TenantController.cs
using AppNameTestify.DBModel;
using AppNameTestify.Helpers;
using AppNameTestify.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace AppNameTestify.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Authorize]
    public class TenantController : Controller
    {
        /// <summary>
        /// The database context
        /// </summary>
        TestifyEntities dbContext = new TestifyEntities();

        /// <summary>
        /// Tickets the details.
        /// </summary>
        /// <returns></returns>
        public ActionResult TicketDetails()
        {
            return View();
        }
        /// <summary>
        /// Gets the ticket lists.
        /// </summary>
        /// <param name="sidx">The sidx.</param>
        /// <param name="sord">The sord.</param>
        /// <param name="page">The page.</param>
        /// <param name="rows">The rows.</param>
        /// <param name="search">The search.</param>
        /// <param name="nd">The nd.</param>
        /// <param name="status">The status.</param>
        /// <returns></returns>
        public JsonResult GetTicketLists(string sidx, string sord, int page, int rows, string search, string nd, string status)
        {
            int tenantId = Convert.ToInt32(FormsAuthentication.Decrypt(Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name);

            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            var ticketList = dbContext.TenantTickets.Where(c => c.TenantId == tenantId && c.IsActive == true && c.Status == status).Select(
                    a => new
                    {
                        a.ID,
                        a.Title,
                        a.Description,
                        a.TenantId,
                        a.IsActive,
                        a.CreatedDate,
                        a.ModifiedDate,
                        a.ApprovedDate,
                        a.Status

                    }).ToList();

            int totalRecords = ticketList.Count();
            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
            if (sord.ToUpper() == "DESC")
            {
                ticketList = ticketList.OrderByDescending(s => s.CreatedDate).ToList();
                ticketList = ticketList.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            else
            {
                ticketList = ticketList.OrderBy(s => s.CreatedDate).ToList();
                ticketList = ticketList.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }

            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = ticketList
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Creates the specified object ticket.
        /// </summary>
        /// <param name="objTicket">The object ticket.</param>
        /// <returns></returns>
        [HttpPost]
        public string Create([Bind(Exclude = "ID")] TenantTicket objTicket)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {
                    int tenantId = Convert.ToInt32(FormsAuthentication.Decrypt(Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name);
                    //  var tenantObj = dbContext.TenantRegistrations.FirstOrDefault(c => c.TenantId == tenantId && c.IsActive == true);
                    objTicket.TenantId = tenantId;
                    objTicket.IsActive = true;
                    objTicket.Status = "Pending";
                    objTicket.CreatedDate = DateTime.Now.ToString();
                    dbContext.TenantTickets.Add(objTicket);
                    dbContext.SaveChanges();
                    //if (tenantObj != null)
                    //{
                    //    var houseObj = dbContext.LandlordHouseDetails.FirstOrDefault(c => c.Id == tenantObj.LandlordPRTBNO);
                    //    var landlordObj = dbContext.LandlordRegistrations.FirstOrDefault(c => c.LandlordId == houseObj.LandlordId);
                    SendReportDetailsToLanlord(3,tenantId, "Tenant Reported New Problem");

                    //}
                    msg = "Saved Successfully";


                }
                else
                {
                    msg = "Validation data not successfull";
                }
            }
            catch (Exception ex)
            {
                msg = "Error occured:" + ex.Message;
            }

            return msg;
        }
        private void SendReportDetailsToLanlord(int emailtempid,int tenantId, string mailSubject)
        {
            try
            {
                var model = dbContext.TenantRegistrations.FirstOrDefault(c => c.TenantId == tenantId && c.IsActive == true);

                if (model != null)
                {
                    var houseObj = dbContext.LandlordHouseDetails.FirstOrDefault(c => c.Id == model.LandlordPRTBNO);
                    var landlordObj = dbContext.LandlordRegistrations.FirstOrDefault(c => c.LandlordId == houseObj.LandlordId);
                    var emailTemplateObj = dbContext.EmailTemplates.FirstOrDefault(c => c.EmailTemplateId == emailtempid);
                    if (emailTemplateObj != null)
                    {
                        var emailBody = emailTemplateObj.EmailBodyTemplate;
                        emailBody = emailBody.Replace("#FirstName", model.FirstName);
                        emailBody = emailBody.Replace("#LastName", model.LastName);
                        emailBody = emailBody.Replace("#PhoneNo", model.PhoneNo);
                        emailBody = emailBody.Replace("#EmailId", model.Email);
                        EmailComponent.SendEmail(landlordObj.Email, mailSubject, emailBody);
                    }
                }
            }
            catch (Exception ex)
            {

            }
            


        }
        /// <summary>
        /// Edits the specified object ticket.
        /// </summary>
        /// <param name="objTicket">The object ticket.</param>
        /// <returns></returns>
        public string Edit(TenantTicket objTicket)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {
                   var ticketObj= dbContext.TenantTickets.FirstOrDefault(c => c.ID == objTicket.ID);
                   if (ticketObj!=null)
                   {
                       
                       objTicket.CreatedDate = ticketObj.CreatedDate;
                       objTicket.ModifiedDate = DateTime.Now.ToString();
                       objTicket.Status = "Pending";
                     //  dbContext.Entry(objTicket).State = EntityState.Modified;
                       dbContext.Entry(ticketObj).CurrentValues.SetValues(objTicket);
                       dbContext.SaveChanges();
                       SendReportDetailsToLanlord(4, Convert.ToInt32(objTicket.TenantId), "Tenant Updated Report Details");

                       msg = "Updated Successfully";
                   }
                   else
                   {
                       msg = "Error occured while updating the details";
                   }
                    



                }
                else
                {
                    msg = "Validation data not successfull";
                }
            }
            catch (Exception ex)
            {
                msg = "Error occured:" + ex.Message;
            }
            return msg;
        }
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="ID">The identifier.</param>
        /// <returns></returns>
        public string Delete(int ID)
        {
            var objTicket = dbContext.TenantTickets.Find(ID);
            objTicket.IsActive = false;
            objTicket.ModifiedDate = DateTime.Now.ToString();
            dbContext.Entry(objTicket).State = EntityState.Modified;
            dbContext.SaveChanges();
            SendReportDetailsToLanlord(5,Convert.ToInt32(objTicket.TenantId), "Tenant Deleted Report Details");

            return "Deleted successfully";
        }



    }
}

final x13125320/AppNameTestify/AppNameTestify/Views/Shared/_LandlordLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
   
  

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/Bootstrap/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/Bootstrap/business-casual.css" rel="stylesheet">
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via  -->
    <!--[if lt IE 9]>
        <script src="~/Scripts/Bootstrap/html5shiv.js"></script>
        <script src="~/Scripts/Bootstrap/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery -->
    <script src="/Scripts/Bootstrap/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Scripts/Bootstrap/bootstrap.min.js"></script>
    <!-- Script to Activate the Carousel --> 

    @*@Styles.Render("~/Content/css")*@
    <link href="@Url.Content("~/Content/Testify.css")" rel="stylesheet" type="text/css" />


</head>
<body>
    <div id="logindisplay" class="logInfo"></div>
    <div class="brand">Testify</div>
    <div class="address-bar"> NCI  | Mayor Square IFSC, Dublin-1 | 086.361.5033</div>
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Testify</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               
                    <ul class="nav navbar-nav">
                        <li>
                            @Html.ActionLink("Manage House", "ManageHouses", "Landlord")
                        </li>
                        <li>
                            @Html.ActionLink("Manage Report", "ManageTicketDetails", "Landlord")
                        </li>
                       
                    </ul>
                    
                
             
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div class="container">
        @RenderBody()
       
    </div>
    <!-- /.container -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Testify 2015</p>
                </div>
            </div>
        </div>
    </footer>
   
    @RenderSection("scripts", required: false)
    
</body>

</html>

final x13125320/AppNameTestify/AppNameTestify/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
   
    <title>@ViewBag.Title</title>
    @*<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="../../Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.20.js")" type="text/javascript"></script>*@ 
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    <link href="@Url.Content("~/Content/Testify.css")" rel="stylesheet" type="text/css" />
    
</head>
<body>
    <div class="page">
        <div id="header">
           
             <div id="logindisplay">
             
            </div>
            
        </div>
        <div id="main">
            @RenderBody()
        </div>
       
    </div>
   
     @RenderSection("scripts", required: false)
</body>
</html>

final x13125320/AppNameTestify/AppNameTestify/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
   
  

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/Bootstrap/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/Bootstrap/business-casual.css" rel="stylesheet">
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="~/Scripts/Bootstrap/html5shiv.js"></script>
        <script src="~/Scripts/Bootstrap/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery -->
    <script src="/Scripts/Bootstrap/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Scripts/Bootstrap/bootstrap.min.js"></script>
    <!-- Script to Activate the Carousel --> 

    @*@Styles.Render("~/Content/css")*@
    <link href="@Url.Content("~/Content/Testify.css")" rel="stylesheet" type="text/css" />


</head>
<body>
    <div class="brand">Testify</div>
    <div class="address-bar"> NCI  | Mayor Square IFSC, Dublin-1 | 086.361.5033</div>
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Testify</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               
                    <ul class="nav navbar-nav">
                        <li>
                            @Html.ActionLink("Home", "Index", "Home")
                        </li>
                        <li>
                            @Html.ActionLink("About", "About", "Home")
                        </li>
                        @*<li>
                            <a href="blog.html">Blog</a>
                        </li>*@
                        <li>
                            @Html.ActionLink("Contact", "Contact", "Home")
                        </li>
                        @*<li id="logindisplay">
                            <a href="contact.html">Contact</a>
                        </li>*@

                    </ul>
                    
                
             
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div class="container">
        @RenderBody()
       
    </div>
    <!-- /.container -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Testify 2015</p>
                </div>
            </div>
        </div>
    </footer>
   
    @RenderSection("scripts", required: false)
    
</body>

</html>

final x13125320/AppNameTestify/AppNameTestify/Views/Shared/_TenantLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
   
  

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/Bootstrap/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/Bootstrap/business-casual.css" rel="stylesheet">
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via  -->
    <!--[if lt IE 9]>
        <script src="~/Scripts/Bootstrap/html5shiv.js"></script>
        <script src="~/Scripts/Bootstrap/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery -->
    <script src="/Scripts/Bootstrap/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Scripts/Bootstrap/bootstrap.min.js"></script>
    <!-- Script to Activate the Carousel --> 

    @*@Styles.Render("~/Content/css")*@
    <link href="@Url.Content("~/Content/Testify.css")" rel="stylesheet" type="text/css" />


</head>
<body>
    <div id="logindisplay" class="logInfo"></div>
    <div class="brand">Testify</div>
    <div class="address-bar"> NCI  | Mayor Square IFSC, Dublin-1 | 086.361.5033</div>
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               
                    <ul class="nav navbar-nav">
                        
                        <li>
                            @Html.ActionLink("Manage Report", "TicketDetails", "Tenant")
                        </li>
                       
                    </ul>
                    
                
             
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div class="container">
        @RenderBody()
       
    </div>
    <!-- /.container -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Testify 2015</p>
                </div>
            </div>
        </div>
    </footer>
   
    @RenderSection("scripts", required: false)
    
</body>

</html>