final x13125320/AppNameTestify/AppNameTestify/Controllers/LandlordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppNameTestify.Models;
using System.Web.Security;
using AppNameTestify.DBModel;
using System.Data;
using AppNameTestify.Helpers;

namespace AppNameTestify.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Authorize]
    public class LandlordController : Controller
    {

        /// <summary>
        /// The database context
        /// </summary>
        TestifyEntities dbContext = new TestifyEntities();

        /// <summary>
        /// Gets the current landlord details.
        /// </summary>
        /// <returns></returns>
        private LandlordRegister GetCurrentLandlordDetails()
        {
            LandlordRegister LandlordModel = new LandlordRegister();
            int userid = Convert.ToInt32(FormsAuthentication.Decrypt(Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name);
            var landlordEntity = dbContext.LandlordRegistrations.FirstOrDefault(r => r.LandlordId == userid && r.IsActive == true);
            if (landlordEntity != null)
            {
                LandlordModel.ID = landlordEntity.LandlordId;
                LandlordModel.FirstName = landlordEntity.FirstName;
                LandlordModel.LastName = landlordEntity.LastName;
                LandlordModel.PPSNNO = landlordEntity.PPSNNO;
            }
            return LandlordModel;


        }
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return null;
            //return View();
        }

        /// <summary>
        /// Manages the houses.
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageHouses()
        {

            return View();
        }


        /// <summary>
        /// Gets the manage house lists.
        /// </summary>
        /// <param name="sidx">The sidx.</param>
        /// <param name="sord">The sord.</param>
        /// <param name="page">The page.</param>
        /// <param name="rows">The rows.</param>
        /// <param name="search">The search.</param>
        /// <param name="nd">The nd.</param>
        /// <returns></returns>
        public JsonResult GetManageHouseLists(string sidx, string sord, int page, int rows, string search, string nd)
        {
            var landlordModel = GetCurrentLandlordDetails();
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            var houseListsResults = dbContext.LandlordHouseDetails.Where(c => c.IsActive == true && c.LandlordId == landlordModel.ID).Select(
                    a => new
                    {
                        a.Id,
                        a.LandlordId,
                        a.PRTBNO,
                        a.Address,
                        a.IsActive

                    }).ToList();

            int totalRecords = houseListsResults.Count();
            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
            if (sord.ToUpper() == "DESC")
            {
                houseListsResults = houseListsResults.OrderByDescending(s => s.PRTBNO).ToList();
                houseListsResults = houseListsResults.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }
            else
            {
                houseListsResults = houseListsResults.OrderBy(s => s.PRTBNO).ToList();
                houseListsResults = houseListsResults.Skip(pageIndex * pageSize).Take(pageSize).ToList();
            }

            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = houseListsResults
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Creates the specified object lanlord house.
        /// </summary>
        /// <param name="objLanlordHouse">The object lanlord house.</param>
        /// <returns></returns>
        [HttpPost]
        public string Create([Bind(Exclude = "Id")] LandlordHouseDetail objLanlordHouse)
        {
            string msg;
            try
            {

                if (ModelState.IsValid)
                {
                    var landLordModel = GetCurrentLandlordDetails();
                    var result = IsPRTBNOExit(landLordModel.ID, objLanlordHouse.PRTBNO.Trim(), 0);
                    if (result == false)
                    {
                        objLanlordHouse.LandlordId = landLordModel.ID;
                        objLanlordHouse.IsActive = true;
                        dbContext.LandlordHouseDetails.Add(objLanlordHouse);
                        dbContext.SaveChanges();
                        msg = "Saved Successfully";
                    }
                    else
                    {
                        msg = "Already PRTBNO is Exists";

                    }

                }
                else
                {
                    msg = "Validation data not successfull";
                }
            }
            catch (Exception ex)
            {
                msg = "Error occured:" + ex.Message;
            }

            return msg;
        }
        /// <summary>
        /// Edits the specified object lanlord house.
        /// </summary>
        /// <param name="objLanlordHouse">The object lanlord house.</param>
        /// <returns></returns>
        public string Edit(LandlordHouseDetail objLanlordHouse)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {
                    var landLordModel = GetCurrentLandlordDetails();
                    var result = IsPRTBNOExit(landLordModel.ID, objLanlordHouse.PRTBNO.Trim(), objLanlordHouse.Id);
                    if (result == false)
                    {
                        dbContext.Entry(objLanlordHouse).State = EntityState.Modified;
                        dbContext.SaveChanges();
                        msg = "Updated Successfully";
                    }
                    else
                    {
                        msg = "Already PRTBNO is Exists";

                    }


                }
                else
                {
                    msg = "Validation data not successfull";
                }
            }
            catch (Exception ex)
            {
                msg = "Error occured:" + ex.Message;
            }
            return msg;
        }
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="Id">The identifier.</param>
        /// <returns></returns>
        public string Delete(int Id)
        {
            LandlordHouseDetail objLanlordHouse = dbContext.LandlordHouseDetails.Find(Id);
            objLanlordHouse.IsActive = false;
            dbContext.Entry(objLanlordHouse).State = EntityState.Modified;
            dbContext.SaveChanges();
            return "Deleted successfully";
        }
        /// <summary>
        /// Determines whether [is prtbno exit] [the specified landlordid].
        /// </summary>
        /// <param name="landlordid">The landlordid.</param>
        /// <param name="PRTBNO">The prtbno.</param>
        /// <param name="houseId">The house identifier.</param>
        /// <returns></returns>
        private bool IsPRTBNOExit(int landlordid, string PRTBNO, int houseId)
        {


            var result = dbContext.LandlordHouseDetails.Where(c => c.LandlordId == landlordid && c.PRTBNO == PRTBNO && c.Id != houseId && c.IsActive == true).ToList();

            if (result != null && result.Count > 0)
            {
                return true;
            }
            return false;

        }
        /// <summary>
        /// Manages the ticket details.
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageTicketDetails()
        {
            int landlordId = Convert.ToInt32(FormsAuthentication.Decrypt(Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name);
            var landlordHouseList = dbContext.LandlordHouseDetails.Where(c => c.LandlordId == landlordId && c.IsActive == true).ToList();
            var houseList = landlordHouseList.Select(
                    a => new HouseModel
                    {
                        Id = a.Id,
                        PRTBNO = a.PRTBNO
                    }).ToList();
            houseList.Insert(0, new HouseModel() { Id = 0, PRTBNO = "--Select PRTBNO--" });
            ViewBag.houseList = new SelectList(houseList, "Id", "PRTBNO");
            return View("ManageTicketDetails");
        }

        /// <summary>
        /// Gets the ticket lists.
        /// </summary>
        /// <param name="sidx">The sidx.</param>
        /// <param name="sord">The sord.</param>
        /// <param name="page">The page.</param>
        /// <param name="rows">The rows.</param>
        /// <param name="search">The search.</param>
        /// <param name="nd">The nd.</param>
        /// <param name="status">The status.</param>
        /// <param name="prtbid">The prtbid.</param>
        /// <returns></returns>
        public JsonResult GetTicketLists(string sidx, string sord, int page, int rows, string search, string nd, string status, int prtbid)
        {
            var tenant = dbContext.TenantRegistrations.FirstOrDefault(c => c.LandlordPRTBNO == prtbid);
            if (tenant != null)
            {
                int pageIndex = Convert.ToInt32(page) - 1;
                int pageSize = rows;
                var ticketList = dbContext.TenantTickets.Where(c => c.TenantId == tenant.TenantId && c.IsActive == true && c.Status == status).Select(
                        a => new
                        {
                            a.ID,
                            a.Title,
                            a.Description,

final x13125320/AppNameTestify/AppNameTestify/Views/Landlord/ManageHouses.cshtml
@model   AppNameTestify.Models.HouseModel
@{
    ViewBag.Title = "Testify";
    Layout = "~/Views/Shared/_LandlordLayout.cshtml";
}
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/Testify.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        LoadLoginPartialView(1);
    });
</script>

<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">
                Manage House Details
                <strong></strong>
            </h2>
            <hr>
            <div>
                @*<div style="float:right;padding-bottom:5px">
                    @Html.ActionLink("Manage Tenant Report", "ManageTicketDetails", "Landlord")
                </div>*@

                <div style="clear:both"></div>
                <div>
                    <table id="grid"></table>
                    <div id="pager"></div>
                </div>
            </div>

        </div>
    </div>
</div>

<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.8.20.min.js"></script>
<script src="~/Scripts/i18n/grid.locale-en.js"></script>
<script src="~/Scripts/jquery.jqGrid.min.js"></script>
<script src="~/Scripts/LandlordHouseList.js"></script>

final x13125320/AppNameTestify/AppNameTestify/Views/Landlord/ManageTicketDetails.cshtml
@model    List<AppNameTestify.Models.HouseModel>

@{
    ViewBag.Title = "Report Details";
    Layout = "~/Views/Shared/_LandlordLayout.cshtml";
}
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/Testify.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#ddlHouse").change(function () {
            //Get DropDownlist selected item index
            var selectedIndex = $(this).find("option:selected").index();
            //Get DropDownlist selected item value
            var selectedValue = $(this).find("option:selected").val();
            //Get DropDownlist selected item text
            var selectedText = $(this).find("option:selected").text();
          
            ReloadPendingTicketsGrid(selectedValue);
            ReloadApprovedTicketsGrid(selectedValue);

        });
    }


    );
    $(document).ready(function () {
        LoadLoginPartialView(1);
        BindTicketDetails(0);
    });

    function BindTicketDetails(prtbid) {

        $("#grid").jqGrid({
            url: "/Landlord/GetTicketLists?status=Pending&prtbid=" + prtbid,
            datatype: 'json',
            mtype: 'Get',
            colNames: ['ID', 'TenantId', 'FirstName', 'LastName', 'Email', 'PhoneNo', 'Title', 'Description', 'IsActive', 'CreatedDate', 'ModifiedDate', 'Status'],
            colModel: [
                { key: true, hidden: true, name: 'ID', index: 'ID', editable: true },
                { key: false, hidden: true, name: 'TenantId', index: 'TenantId', editable: true },
                { key: false, name: 'FirstName', index: 'FirstName', editable: true, editoptions: { readonly: true, size: 26 } },
                { key: false, name: 'LastName', index: 'LastName', editable: true, editoptions: { readonly: true, size: 26 } },
                { key: false, name: 'Email', index: 'Email', editable: true, editoptions: { readonly: true, size: 26 } },
                { key: false, name: 'PhoneNo', index: 'PhoneNo', editable: true, editoptions: { readonly: true, size: 26 } },
                { key: false, name: 'Title', index: 'Title', editable: true, editoptions: { readonly: true, size: 26 } },
                { key: false, name: 'Description', index: 'Description', editable: true,  edittype: 'textarea', editoptions: { readonly: true, rows: "8", cols: "26" } },
                { key: false, hidden: true, name: 'IsActive', index: 'IsActive', editable: true },
                { key: false,  name: 'CreatedDate', index: 'CreatedDate', editable: false},
                { key: false, name: 'ModifiedDate', index: 'ModifiedDate', editable: false },
                { key: false, name: 'Status', index: 'Status', editable: true, edittype: 'select', editoptions: { value: { 'Pending': 'Pending', 'Approved': 'Approved' }} }

            ],
            pager: jQuery('#pager'),
            rowNum: 10,
            rowList: [10, 20, 30, 40],
            height: '100%',
            viewrecords: true,
            caption: 'Pending Report Details',
            emptyrecords: 'No records to display',
            jsonReader: {
                root: "rows",
                page: "page",
                total: "total",
                records: "records",
                repeatitems: false,
                Id: "0"
            },
            autowidth: true,
            multiselect: false
        }).navGrid('#pager', { edit: true, add: false, del: false, search: false, refresh: true },
        {
            // edit options
            zIndex: 100,
            autowidth: true,
            autoheight: true,
            url: '/Landlord/EditTicket',
            closeOnEscape: true,
            closeAfterEdit: true,
            recreateForm: true,
            afterComplete: function (response) {
                if (response.responseText) {

                    ReloadApprovedTicketsGrid($("#ddlHouse").find("option:selected").val());
                    alert(response.responseText);
                }
            }
        }

        );


        //Approved Tickets GridView
        $("#grid1").jqGrid({
            url: "/Tenant/GetTicketLists?status=Approved&prtbid=" + prtbid,
            datatype: 'json',
            mtype: 'Get',
            colNames: ['ID', 'TenantId', 'FirstName', 'LastName', 'Email', 'PhoneNo', 'Title', 'Description', 'IsActive', 'CreatedDate', 'ModifiedDate','ApprovedDate', 'Status'],
            colModel: [
                { key: true, hidden: true, name: 'ID', index: 'ID', },
                { key: false, hidden: true, name: 'TenantId', index: 'TenantId' },
                 { key: false, name: 'FirstName', index: 'FirstName' },
                { key: false, name: 'LastName', index: 'LastName'},
                { key: false, name: 'Email', index: 'Email' },
                { key: false, name: 'PhoneNo', index: 'PhoneNo' },
                { key: false, name: 'Title', index: 'Title' },
                { key: false, name: 'Description', index: 'Description' },
                { key: false, hidden: true, name: 'IsActive', index: 'IsActive' },
                { key: false,  name: 'CreatedDate', index: 'CreatedDate' },
                { key: false,  name: 'ModifiedDate', index: 'ModifiedDate' },
                { key: false, name: 'ApprovedDate', index: 'ApprovedDate'},
                { key: false, name: 'Status', index: 'Status' }
            ],
            pager: jQuery('#pager1'),
            rowNum: 10,
            rowList: [10, 20, 30, 40],
            height: '100%',
            viewrecords: true,
            caption: 'Approved Report Details',
            emptyrecords: 'No records to display',
            jsonReader: {
                root: "rows",
                page: "page",
                total: "total",
                records: "records",
                repeatitems: false,
                Id: "0"
            },
            autowidth: true,
            multiselect: false
        }).navGrid('#pager1', { edit: false, add: false, del: false, search: false, refresh: true }


            );
    }
    function ReloadPendingTicketsGrid(prtbid) {
        //For Pending Tickets Reload
        var url = "/Landlord/GetTicketLists?status=Pending&prtbid=" + prtbid;
        $("#grid").jqGrid('setGridParam', { url: url });
        $("#grid").trigger("reloadGrid");

    }
    function ReloadApprovedTicketsGrid(prtbid) {


        //For Approved Tickets Reload
        var url = "/Landlord/GetTicketLists?status=Approved&prtbid=" + prtbid;
        $("#grid1").jqGrid('setGridParam', { url: url });
        $("#grid1").trigger("reloadGrid");
    }
</script>

<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">
                Manage Report Details
                <strong></strong>
            </h2>
            <hr>
            <div>
                @*<div style="float:right;padding-bottom:5px">
                    @Html.ActionLink("Manage Houses", "ManageHouses", "Landlord")
                </div>*@
                <div style="padding-bottom:10px;text-align:center">Select PRTB NO @Html.DropDownList("ddlHouse", ViewBag.houseList as SelectList)</div>
                <div>
                    <table id="grid"></table>
                    <div id="pager"></div>
                </div>
                <div style="padding-top:30px">
                    <table id="grid1"></table>
                    <div id="pager1"></div>
                </div>
                
            </div>

        </div>
    </div>
</div>

<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.8.20.min.js"></script>
<script src="~/Scripts/i18n/grid.locale-en.js"></script>
<script src="~/Scripts/jquery.jqGrid.min.js"></script>

final x13125320/AppNameTestify/AppNameTestify/Views/Landlord/_LandlordHousesView.cshtml
@using AppNameTestify.Models
@model List<AppNameTestify.Models.UserModel>


<style type="text/css">
    
    .webgrid-table
    {
        font-family: Arial,Helvetica,sans-serif;
        font-size: 14px;
        font-weight: normal;
        width: 650px;
        display: table;
        border-collapse: collapse;
        border: solid px #C5C5C5;
        background-color: white;
    }
    .webgrid-table td, th
    {
        border: 1px solid #C5C5C5;
        padding: 3px 7px 2px;
    }
    .webgrid-header, .webgrid-header a
    {
        background-color: #E3E3E3;
        color: black;
        text-align: left;
        text-decoration:none;
    }
    .webgrid-footer
    {
        padding: inherit
    }
    .webgrid-row-style
    {
        padding: 3px 7px 2px;
    }
    .webgrid-alternating-row
    {
        background-color: #F5F5F5;
        padding: 3px 7px 2px;
    }
    .col1Width
    {
        width: 50px;
    }
    .col2Width
    {
        width: 200px;
    }
</style>
<script type="text/javascript" >
    
    $(function () {
        $('.edit-mode').hide();
        $('.edit-user, .cancel-user').on('click', function () {
            var tr = $(this).parents('tr:first');
            tr.find('.edit-mode, .display-mode').toggle();
        });

        $('.save-user').on('click', function () {
            var tr = $(this).parents('tr:first');
            var Name = tr.find("#Name").val();
            var SurName = tr.find("#SurName").val();
            var UserID = tr.find("#UserID").html();
            tr.find("#lblName").text(Name);
            tr.find("#lblSurName").text(SurName);
            tr.find('.edit-mode, .display-mode').toggle();
            var UserModel =
            {
                "ID": UserID,
                "Name": Name,
                "SurName": SurName
            };
            $.ajax({
                url: '/User/ChangeUser/',
                data: JSON.stringify(UserModel),
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    alert(data);
                }
            });

        });
    })
</script>

@{
    var user = new UserModel();
    user.ID = 1;
    var userList = new List<UserModel>();
    userList.Add(user);
    var grid = new WebGrid(userList);
}

<div  id="gridContent" style=" padding-left: 190px; " >
@grid.GetHtml(
        tableStyle: "webgrid-table",
        headerStyle: "webgrid-header",
        footerStyle: "webgrid-footer",
        alternatingRowStyle: "webgrid-alternating-row",
        selectedRowStyle: "webgrid-selected-row",
        rowStyle: "webgrid-row-style",
        mode: WebGridPagerModes.All,
        columns:
            grid.Columns(
             grid.Column("ID", format: @<text>  <span  class="display-mode">@item.ID </span> <label id="UserID" class="edit-mode">@item.ID</label> </text>, style: "col1Width" ),
             grid.Column("Name", "Name", format: @<text>  <span  class="display-mode"> <label id="lblName"  >@item.Name</label> </span> <input type="text" id="Name" value="@item.Name" class="edit-mode" /></text>, style: "col2Width",canSort: false),
             grid.Column("SurName", "Sur Name", format: @<text> <span  class="display-mode"> <label id="lblSurName">@item.SurName</label> </span>  <input type="text"  id="SurName" value="@item.SurName" class="edit-mode" /> </text>, style: "col2Width",canSort: false), 
             grid.Column("Action", format: @<text>
                                <button class="edit-user display-mode" >Edit</button>
                                <button class="save-user edit-mode"  >Save</button>
                                <button class="cancel-user edit-mode" >Cancel</button>
                            </text>,  style: "col3Width" , canSort: false)
           ))
</div>